### ISSUE TITLE
Feature Request: Lines of Code warning

### ISSUE THREAD

**Issue by tscottjendev** [StefanMaron/BusinessCentral.LinterCop#211]
I didn't see a rule about this.

Could we have a rule that gave a warning/info if the number of lines of code in a procedure exceeds a definable value?  I would default it to something like 40 or 50 and have a setting for it in LinterCop.json.

Too many lines of code in a procedure can imply that the code could be functionalized better.

**Comment by rvanbekkum** [comment]
I think rule [LC011](https://github.com/StefanMaron/BusinessCentral.LinterCop/wiki/LC0011) might cover that mostly, not? 😊
The maintainability index incorporates the "lines of code" in the calculation.

**Comment by tscottjendev** [comment]
I agree but a lot of things go into Maintainability Index.  A Lines of Code metric is a simpler measure to understand.  Reducing lines of code will affect Maintainability Index without having to try and dissect what goes into the Maintainability Index.

**Comment by StefanMaron** [comment]
Not so sure how much value that rule would be of. 
From my experience, when a procedure has a warning about complexity, and you refactor that function to be less complex, you do not need to care what exactly is used to calculate complexity.

Can you give an example where you would consider a procedure nice an readable but still get the warning?

**Comment by tscottjendev** [comment]
I just feel it is a simpler metric than MI or CC to understand.  With a "good" MI ranging from 20 - 100 it is difficult to explain that it can be made better.  If MI is over 20 then a developer thinks great, that is good code, but it can have 40 lines of code in a procedure and that is likely less good than it could be.

**Comment by StefanMaron** [comment]
Then again, 40 maybe even 80 lines of code in one procedure may be perfectly valid at one point but a complete mess in another point.
Expecially when moving data and filling a lot of fields, you quickly have a lot of code. In such an example, for me, it would be bad code if that gets split just to avoid a no of lines warning.

I dont think that I would want to add this to the linter, because 1 its (mostly) covered by the Code Complexity warning we already have, and 2 because I think this metric could be even too simple and generate to many false postives.

But I do plan to do a stram/video maybe session at Dynamics con or something where I show how everyone can create their own analyzers and this maybe a good example rule

**Comment by tscottjendev** [comment]
That's fine @StefanMaron.  Sounds like a great idea for a session.
