### ISSUE TITLE
Documentation for LC0021, LC0022 and LC0023 missing in Wiki

### ISSUE THREAD

**Issue by rvanbekkum** [StefanMaron/BusinessCentral.LinterCop#245]
Noticed that there are no Wiki pages for the new rules LC0021, LC0022, LC0023.
When there are wiki pages the hyperlinks should be updated as well. :)

**Comment by mortenseifert** [comment]
Where does the LC0021 requirement/warning come from? The documentation does not state that we should do something different. I understand that the **Confirm Management** allows does offer the option of returning a default selection when running unattended. But in may cases I don't want a default response.

https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/dialog/dialog-confirm-method

**Comment by Arthurvdv** [comment]
Hi @mortenseifert,

I've started the discussion for the rule LC0021 here: https://github.com/StefanMaron/BusinessCentral.LinterCop/discussions/205 (where I've described what I believe are the benefits).

I'm guessing [GetResponse](https://github.com/microsoft/ALAppExtensions/tree/main/Modules/System/Confirm%20Management#getresponse-method-) function is the best fit for your Use Case to not set a default response. If I read de documentation of both, this will have the same behavior?

![image](https://user-images.githubusercontent.com/44637996/223172941-d007f6ef-333b-43c2-8a8e-718f25c76707.png)
https://github.com/microsoft/ALAppExtensions/tree/main/Modules/System/Confirm%20Management#getresponse-method-

![image](https://user-images.githubusercontent.com/44637996/223173115-918c6d67-83ae-4a4b-b0bf-baf83c562ddf.png)
https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods-auto/dialog/dialog-confirm-method#parameters

If the goal is to throw an error when running unattended, because that is what the default Dialog.Confirm() function does if I'm not mistaking, doesn't it make more sense to have a pre-flight check on the IsGuiAllowed() an throw an error on this, before reaching the Dialog.Conform() code?

If I'm missing something here, I would love to hear more about your Use Case and maybe we can improve the LC0021 rule together.

**Comment by mortenseifert** [comment]
@Arthurvdv thanks for updating me - I missed #205 when trying to figure out why the rule was created. I am still not convinced that this should be a rule; but then we have app.ruleset.json, so I can the the mind of BC LinterCop :)

**Comment by Arthurvdv** [comment]
@rvanbekkum Thank you for bringing this to our attention. In this thread it's also noticeable that it helps to explain why a certain rule is raised and what the underlying idea of this rule is. I've created the wiki pages, so all links should resolve now.
