### ISSUE TITLE
Overview of rules

### ISSUE THREAD

**Issue by fvet** [StefanMaron/BusinessCentral.LinterCop#351]
There seems to be 2 places where a list of rules is maintained:

- https://github.com/StefanMaron/BusinessCentral.LinterCop/blob/master/README.md#rules (which does contain the default actions, but lacks the latest rules)
- https://github.com/StefanMaron/BusinessCentral.LinterCop/wiki/ (which contains all rules, but not the default actions)

Might be good to consolidate both into one page, so adding new rules is only required on one location.

**Comment by Arthurvdv** [comment]
This is "by design" I believe.

In the wiki the rules for the Pre-Release are already there, where the master branch reflects the Latest release. You're right that this is a bit of extra housekeeping to maintain the both places, but for me it isn't an issue.

Of is there maybe a better approach to manage this?
