### ISSUE TITLE
LinterCop is compiled with debug configuration

### ISSUE THREAD

**Issue by dannoe** [StefanMaron/BusinessCentral.LinterCop#457]
Is this intentional?

If not, I would recommend building with the release configuration in the pipeline. With debug, the compiler will not optimize the assembly. This improves performance even more.

**Comment by Arthurvdv** [comment]
> Is this intentional?

I'm not aware if this was intentional, could be it just works™ settings 😅

Thank you for suggesting this, I didn't realize the difference between Debug and Release. I've updated the (pre)release [v0.30.10](https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/tag/v0.30.10) version of the LinterCop which is build with the Release configuration.

**Comment by jwikman** [comment]
This seems to have reduced the overall time consumed by LC with 15-20% 👍

Any ETA of the release of v.0.30.10?
Asking since I was bit eager and removed some now, in pre-release, unnecessary pragmas. But I just realized that our pipelines are not running pre-release version and hence failed. 😅

**Comment by jwikman** [comment]
Thanks @Arthurvd! 🥳
