### ISSUE TITLE
LC0068 - Triggering on TableExt/PageExt

### ISSUE THREAD

**Issue by tkroes** [StefanMaron/BusinessCentral.LinterCop#725]
The `Permissions` property can not be modified on Table Extensions and Page Extensions. This means that, if there are triggers or actions in a page extension that require additional permissions to access table data for instance, an info is produced that can not be directly solved by adding a `Permissions` property to the object. The solution may very well be "just move the offending code to a codeunit and set permissions there", but I figured I'd at least make an issue to ask whether or not this is intended behaviour.

**Comment by StefanMaron** [comment]
This was intended.

There was a debate about this very question. 
The intention of that rule is to inform the developer about missing indirect permissions. 
Whether or not the permissions can be added on extension objects does not change the fact that the permissions are missing in order to enable usage of indirect permissions in permission sets.
